apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-demo
  template:
    metadata:
      labels:
        app: openshift-demo
    spec:
      containers:
        - name: app
          image: your-dockerhub-username/openshift-demo:latest
          ports:
            - containerPort: 3000
